[shell]
program = "/usr/local/bin/fish"

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#616E88" # "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"

# [colors]
# draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#606d86"
# blue = "#81a1c1"
# cyan = "#8fbcbb"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#eceff4"
# yellow = "#ebcb8b"

# [colors.cursor]
# cursor = "#d8dee9"
# text = "#2e3440"

# [colors.dim]
# black = "#373e4d"
# blue = "#68809a"
# cyan = "#6d96a5"
# green = "#809575"
# magenta = "#8c738c"
# red = "#94545d"
# white = "#aeb3bb"
# yellow = "#b29e75"

# [colors.normal]
# black = "#3b4252"
# blue = "#81a1c1"
# cyan = "#88c0d0"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#e5e9f0"
# yellow = "#ebcb8b"

# [colors.primary]
# background = "#2e3440"
# dim_foreground = "#a5abb6"
# foreground = "#d8dee9"

# [colors.search.matches]
# background = "#88c0d0"
# foreground = "CellBackground"

# [colors.selection]
# background = "#4c566a"
# text = "CellForeground"

# [colors.vi_mode_cursor]
# cursor = "#d8dee9"
# text = "#2e3440"

[cursor.style]
blinking = "Never"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 21

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Light Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 8
y = 8

[env]
TERM = "xterm-256color"
